[tool.poetry]
name = "poker-dash-board"
version = "0.1.0"
description = ""
authors = ["Frederico Wieser <frederico.wieser@gmail.com>"]
readme = "README.md"
packages = [{include = "poker_dash_board"}]

[tool.poetry.dependencies]
python = "^3.11"
numpy = "^1.24.3"
streamlit = "^1.22.0"
matplotlib = "^3.7.1"
streamlit-plotly-events = "^0.0.6"
ipdb = "^0.13.13"

[tool.poetry.group.dev.dependencies]
pandas = "^2.0.1"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
